### ISSUE TITLE
Question: Get telemetry from repeater node

### ISSUE THREAD

**Issue by jeroen94704** [meshcore-dev/meshcore-ha#30]
I'd like to retrieve the telemetry from my remote repeater nodes to log and monitor battery/solar power status. Can this be done with the current version of the integration, e.g. through the CLI card? Telemetry is requested by sending a packet of type "Request" with request type set to 0x03.

**Comment by jeroen94704** [comment]
Wow, in the list of most helpful responses I ever received online this is definitely a contender for the top spot! Thanks!

I got to the point where I do get a telemetry response from the repeater. Unfortunately, once the payload gets to the response handler, it seems to contain only a single telemetry value (It doesn't look truncated, but I upped the "max" value in the input_text config regardless, but that doesn't make a difference):

```json
{"event_type":"EventType.TELEMETRY_RESPONSE","payload":{"pubkey_pre":"be44fbd31bad","lpp":[{"channel":1,"type":"voltage","value":5.2}]},"timestamp":1749581101.780137}
```

When I perform the same request directly with the meshcore Python module, I get much more data:

```
{'pubkey_pre': 'be44fbd31bad', 'lpp': [{'channel': 1, 'type': 'voltage', 'value': 5.2}, {'channel': 1, 'type': 'gps', 'value': {'latitude': 0.0, 'longitude': 0.0, 'altitude': 0.0}}, {'channel': 2, 'type': 'voltage', 'value': 5.25}, {'channel': 2, 'type': 'current', 'value': 0.01}, {'channel': 2, 'type': 'power', 'value': 0.0}, {'channel': 3, 'type': 'voltage', 'value': 0.0}, {'channel': 3, 'type': 'current', 'value': 0.0}, {'channel': 3, 'type': 'power', 'value': 0.0}, {'channel': 4, 'type': 'voltage', 'value': 12.44}, {'channel': 4, 'type': 'current', 'value': 0.009}, {'channel': 4, 'type': 'power', 'value': 0.0}]}
```

Not sure if this is something that gets lost in the underlying HomeAssistant system or in this plugin (e.g. in sanitize_event_data?).

**Comment by awolden** [comment]
I just published a new version `2.0.5` of the integration with the latest version of the py lib. Can you upgrade and see if you are still experiencing the issue?

**Comment by jeroen94704** [comment]
Unfortunately that does not seem to make a difference. I checked that the version of meshcore_py installed in the container running HA is the correct one, and ran the "serial_repeater_telemetry" example from inside the container as well. That gave me all expected telemetry data from the remote repeater node. 

For some reason, between the meshcore_py "handle_rx" function dispatching the event (reader.py, line 437) and the event reaching the "forward_all_events" function in the plugin, all but the first element of the "lpp" list disappear.

**Comment by jeroen94704** [comment]
So the answer is "yes" :). But the response is now too long for HA to handle:

    State {'event_type': 'EventType.TELEMETRY_RESPONSE', 'payload' ...</snip> ...'timestamp': 1749639301.444291} for input_text.myrepeater_telemetry_data is longer than 255, falling back to unknown

Not sure if there's a way around this, but at least it's progress

**Comment by jeroen94704** [comment]
Ok, cracked it :). I couldn't use the input_text because of the 255 character limit, so I had to define triggered template sensors directly like so:

```json
- triggers:
    - trigger: event
      event_type: meshcore_raw_event
      event_data:
        event_type: EventType.TELEMETRY_RESPONSE

  conditions:
    - condition: template
      value_template: "{{ trigger.event.data.payload.pubkey_pre == '<REPEATER_PUB_KEY>' }}"

  sensor:
    - name: "<NAME> repeater Vbatt"
      unique_id: <name>_repeater_vbatt
      state: >
        {% set data = trigger.event.data.payload %}
        {% if data and data != 'unknown' and data != '' %}
          {{ data.lpp[8].value | default(None) }}
        {% endif %}
```

Repeat 5 times, and I can now plot pretty graphs of the Solar panel, battery and supply voltages and currents.

**Comment by awolden** [comment]
Amazing! Thanks for prototyping that out. I knew it could work in theory but hadn't tried it yet. I will summarize this implementation document it for other folks

**Comment by jeroen94704** [comment]
Great! Note that one can define multiple sensors under the same trigger, like this (also improved the sensor definitions to include device class and units):

```yaml
- triggers:
    - trigger: event
      event_type: meshcore_raw_event
      event_data:
        event_type: EventType.TELEMETRY_RESPONSE

  conditions:
    - condition: template
      value_template: "{{ trigger.event.data.payload.pubkey_pre == '<pubkey>' }}"

  sensor:
    - name: "my repeater Vbatt"
      unique_id: my_repeater_vbatt
      state: >
        {% set data = trigger.event.data.payload %}
        {% if data and data != 'unknown' and data != '' %}
          {{ data.lpp[8].value | default(None) }}
        {% endif %}
      unit_of_measurement: "V"
      device_class: voltage
      state_class: measurement

    - name: "My repeater Ibatt"
      unique_id: my_repeater_ibatt
      state: >
        {% set data = trigger.event.data.payload %}
        {% if data and data != 'unknown' and data != '' %}
          {{ data.lpp[9].value * 1000.0 | default(None) }}
        {% endif %}
      unit_of_measurement: "mA"
      device_class: current
      state_class: measurement
```
